name: 张玉洁的组件-yichang
description: 描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十
keywords:
  - 张玉洁的标签
  - network
  - websocket
  - Network
  - NETWORK
  - gsg
  - 如何替换


license: MMMMMMM                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

logo: http://pic35.nipic.com/20131106/6608733_141749725000_2.png
source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
